apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-deplo
  labels:
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: jeto
  template:
    metadata:
      labels:
        tier: jeto
    spec:
      containers:
      - name: dep
        image: httpd:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache-svc
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
  - name: apache
    port: 80
    targetPort: 80
    nodePort: 30000