apiVersion: v1
kind: Pod
metadata:
  name: day1
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
    requests:
      cpu: "100m"
      memory: "64Mi"
    limits:
      cpu: "50m"
      memory: "32Mi"
    ports:
    - containerPort: 80

