apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rss
  labels:
    env: trail1
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: front
  template:
    metadata:
      labels:
        tier: front
    spec:
      containers:
      - name: jenkins
        image: us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5
        ports:
        - containerPort: 90
