apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rss
  labels:
    env: trail1
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: front  # Corrected from 'friont' to 'front'
  template:
    metadata:
      labels:
        tier: front  # Corrected from 'backenf' to 'front'
    spec:
      containers:
      - name: jenkins  # Corrected spelling of 'jenkisns'
        image: us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5
        ports:
        - containerPort: 90
