apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    name: new-pod
spec:
  containers:
  - name: nginxserver
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
