apiVersion: v1
kind: Pod
metadata:
  name: second-pod
  labels:
    app: newlable
spec:
  containers:
  - name: apachecontainer
    image: httpd
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
      name: http
