apiVersion: v1
kind: Pod
metadata:
  name: thirdpod
  labels:
    app: customservice
spec:
  containers:
  - name: customserver
    image: sivaramaprasaditrajula/netflix:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8081
      name: custom-port
