apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    app: jenkinspro
spec:
  containers:
  - name: jen
    image: jenkins/jenkins:lts-jdk17
    ports:
    - containerPort: 8080
    imagePullPolicy: IfNotPresent


---
apiVersion: v1
kind: Service
metadata:
  name: jenkinsproase
  labels:
    app: jenkinsproact
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    app: jenkinspro
