apiVersion: v1
kind: Pod
metadata:
  name: jenkinspod
  labels:
    name: ljenk
spec:
  containers:
  - name: jenkinscontent
    image: jenkins/jenkins:lts-jdk17
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "100m"
        memory: "500Mi"
    ports:
    - containerPort: 8080
